// Generated by CoffeeScript 2.6.1
(function() {
  window._HS = function(e) {
    return console.log(["HS", e]);
  };

  // window.HS_SERVER = 'nb.local.host:3030'
  window.HS_SERVER = 'www.hackersmacker.org';

  window.HSGraph = class HSGraph {
    constructor() {
      this.attachRaters = this.attachRaters.bind(this);
      this.auth_token = null;
      this.stored_username = null;
      this.verified = false;
      this.loadAuthToken(() => {
        return this.decorateComments();
      });
    }

    loadAuthToken(callback) {
      var ref, ref1;
      if (typeof chrome !== "undefined" && chrome !== null ? (ref = chrome.runtime) != null ? ref.sendMessage : void 0 : void 0) {
        return chrome.runtime.sendMessage({
          action: 'getAuthToken'
        }, (response) => {
          this.auth_token = (response != null ? response.auth_token : void 0) || null;
          this.stored_username = (response != null ? response.username : void 0) || null;
          this.verified = !!this.auth_token;
          return callback();
        });
      } else if (typeof browser !== 'undefined' && (typeof browser !== "undefined" && browser !== null ? (ref1 = browser.runtime) != null ? ref1.sendMessage : void 0 : void 0)) {
        return browser.runtime.sendMessage({
          action: 'getAuthToken'
        }, (response) => {
          this.auth_token = (response != null ? response.auth_token : void 0) || null;
          this.stored_username = (response != null ? response.username : void 0) || null;
          this.verified = !!this.auth_token;
          return callback();
        });
      } else {
        return callback();
      }
    }

    storeAuthToken(token, username) {
      var msg, ref, ref1;
      this.auth_token = token;
      this.stored_username = username;
      this.verified = true;
      msg = {
        action: 'setAuthToken',
        auth_token: token,
        username: username
      };
      if (typeof chrome !== "undefined" && chrome !== null ? (ref = chrome.runtime) != null ? ref.sendMessage : void 0 : void 0) {
        return chrome.runtime.sendMessage(msg);
      } else if (typeof browser !== 'undefined' && (typeof browser !== "undefined" && browser !== null ? (ref1 = browser.runtime) != null ? ref1.sendMessage : void 0 : void 0)) {
        return browser.runtime.sendMessage(msg);
      }
    }

    clearAuthToken() {
      var msg, ref, ref1;
      this.auth_token = null;
      this.stored_username = null;
      this.verified = false;
      msg = {
        action: 'clearAuthToken'
      };
      if (typeof chrome !== "undefined" && chrome !== null ? (ref = chrome.runtime) != null ? ref.sendMessage : void 0 : void 0) {
        return chrome.runtime.sendMessage(msg);
      } else if (typeof browser !== 'undefined' && (typeof browser !== "undefined" && browser !== null ? (ref1 = browser.runtime) != null ? ref1.sendMessage : void 0 : void 0)) {
        return browser.runtime.sendMessage(msg);
      }
    }

    decorateComments() {
      var found;
      found = this.findCurrentUser();
      if (!found) {
        return;
      }
      this.findUsernames();
      this.loadRelationships();
      return this.attachSharers();
    }

    findCurrentUser() {
      var $pageTop;
      $pageTop = $('.pagetop a[href^=user]').eq(0);
      if ($pageTop.length === 0) {
        console.log("Please login to use Hacker Smacker");
        return false;
      }
      this.me = $pageTop.attr('href').replace('user?id=', '');
      // Check if stored token matches current user
      if (this.auth_token && this.stored_username === this.me) {
        this.verified = true;
        return true;
      } else if (this.auth_token && this.stored_username !== this.me) {
        // User switched accounts
        this.clearAuthToken();
        this.showWelcome();
        return true;
      } else {
        // No stored token — first time or unverified
        this.checkVerificationStatus();
        return true;
      }
    }

    checkVerificationStatus() {
      if (!this.me) {
        return;
      }
      return $.ajax({
        url: `${window.location.protocol}//${HS_SERVER}/verify/status`,
        data: {
          me: this.me
        },
        dataType: 'json',
        success: (response) => {
          if (response.status === 'unverified') {
            return this.showWelcome();
          }
        }
      });
    }

    // ============================================================
    // First-time user experience
    // ============================================================
    showWelcome() {
      var $banner;
      if ($('.HS-verify-banner').length > 0) {
        return;
      }
      $banner = $(`<tr><td colspan="2">
<div class="HS-verify-banner" style="
    background: linear-gradient(to bottom, #FFFEF7, #FFF9E6);
    border: 1px solid #E0D8B8;
    padding: 14px 18px;
    margin: 6px 8px;
    font-size: 12px;
    font-family: Verdana, Geneva, sans-serif;
    color: #333;
    border-radius: 4px;
    line-height: 1.7;
    box-shadow: 0 1px 3px rgba(0,0,0,0.06);
">
    <div style="margin-bottom: 8px;">
        <strong style="font-size: 13px; color: #2C2416;">Welcome to Hacker Smacker!</strong>
    </div>
    <div style="color: #5C5444;">
        Rate commenters as <span style="color: #4F934D; font-weight: bold;">friends</span> or
        <span style="color: #AC473B; font-weight: bold;">foes</span> using the orbs next to each name.
        You'll also see your friends' ratings (friend-of-a-friend).
    </div>
    <div style="margin-top: 10px; padding-top: 10px; border-top: 1px solid #EDE8D6;">
        <strong>To get started,</strong> verify you own this HN account (takes 30 seconds):
        <a href="#" class="HS-verify-start" style="
            color: #fff;
            background: #96592A;
            padding: 4px 12px;
            border-radius: 3px;
            text-decoration: none;
            font-weight: bold;
            font-size: 11px;
            margin-left: 8px;
            display: inline-block;
        ">Verify my account &rarr;</a>
    </div>
</div>
</td></tr>`);
      $('table#hnmain > tbody').children().eq(0).after($banner);
      return $('.HS-verify-start').on('click', (e) => {
        e.preventDefault();
        return this.startVerification();
      });
    }

    showVerifyNudge() {
      var $banner;
      // Shown when an unverified user tries to click a rating orb
      if ($('.HS-verify-nudge').length > 0) {
        return;
      }
      // Scroll to and highlight the banner if it exists
      $banner = $('.HS-verify-banner');
      if ($banner.length) {
        $banner.css('box-shadow', '0 0 0 3px #E6D950, 0 2px 8px rgba(0,0,0,0.1)');
        $('html, body').animate({
          scrollTop: $banner.offset().top - 50
        }, 300);
        return setTimeout((function() {
          return $banner.css('box-shadow', '0 1px 3px rgba(0,0,0,0.06)');
        }), 2000);
      } else {
        return this.showWelcome();
      }
    }

    startVerification() {
      return $.ajax({
        url: `${window.location.protocol}//${HS_SERVER}/verify/start`,
        data: {
          me: this.me
        },
        dataType: 'json',
        success: (response) => {
          if (response.code === 1) {
            return this.showTokenInstructions(response.verification_token);
          } else if (response.code === 2) {
            if (response.verification_token) {
              return this.showTokenInstructions(response.verification_token);
            }
          }
        }
      });
    }

    showTokenInstructions(token) {
      $('.HS-verify-banner').html(`<div style="line-height: 1.8;">
    <div style="margin-bottom: 10px;">
        <strong style="font-size: 13px; color: #2C2416;">Verify your account</strong>
        <span style="color: #8A8272; font-size: 11px; margin-left: 8px;">Almost done!</span>
    </div>
    <div style="
        background: #F8F5EB;
        border: 1px solid #E0D8B8;
        border-radius: 4px;
        padding: 12px 16px;
        margin-bottom: 12px;
    ">
        <div style="margin-bottom: 8px;">
            <span style="
                background: #96592A;
                color: #fff;
                padding: 1px 7px;
                border-radius: 10px;
                font-size: 11px;
                font-weight: bold;
                margin-right: 6px;
            ">1</span>
            <a href="https://news.ycombinator.com/user?id=${this.me}" target="_blank" style="
                color: #96592A;
                font-weight: bold;
            ">Open your HN profile</a>
            and add this anywhere in your <em>about</em> section:
        </div>
        <div style="text-align: center; margin: 8px 0;">
            <code style="
                background: #fff;
                padding: 6px 14px;
                border-radius: 3px;
                font-size: 13px;
                user-select: all;
                border: 1px solid #DDD8C8;
                letter-spacing: 0.5px;
                cursor: text;
            ">${token}</code>
        </div>
        <div style="font-size: 11px; color: #8A8272; text-align: center;">
            Click the code to select it, then copy &amp; paste into your profile.
        </div>
    </div>
    <div>
        <span style="
            background: #96592A;
            color: #fff;
            padding: 1px 7px;
            border-radius: 10px;
            font-size: 11px;
            font-weight: bold;
            margin-right: 6px;
        ">2</span>
        After saving your profile, come back here and
        <a href="#" class="HS-verify-check" style="
            color: #fff;
            background: #4F934D;
            padding: 4px 12px;
            border-radius: 3px;
            text-decoration: none;
            font-weight: bold;
            font-size: 11px;
            margin-left: 4px;
        ">Check now</a>
        <span class="HS-verify-status" style="color: #8A8272; margin-left: 8px; font-size: 11px;"></span>
    </div>
    <div style="margin-top: 8px; font-size: 11px; color: #8A8272;">
        You can remove the token from your profile after verification.
    </div>
</div>`);
      this._verifyAttempt = 0;
      $('.HS-verify-check').on('click', (e) => {
        e.preventDefault();
        return this.pollVerification();
      });
      // Start auto-polling after a delay
      return setTimeout((() => {
        return this.pollVerification();
      }), 8000);
    }

    pollVerification() {
      this._verifyAttempt = this._verifyAttempt || 0;
      $('.HS-verify-status').text('Checking...');
      return $.ajax({
        url: `${window.location.protocol}//${HS_SERVER}/verify/check`,
        data: {
          me: this.me
        },
        dataType: 'json',
        success: (response) => {
          var retryAfter;
          if (response.status === 'verified') {
            this.storeAuthToken(response.auth_token, this.me);
            return this.showVerified();
          } else if (response.status === 'pending') {
            this._verifyAttempt++;
            retryAfter = response.retry_after || 10;
            $('.HS-verify-status').text(`Not found yet. Will check again in ${retryAfter}s...`);
            return setTimeout((() => {
              return this.pollVerification();
            }), retryAfter * 1000);
          } else if (response.status === 'rate_limited') {
            retryAfter = response.retry_after || 20;
            $('.HS-verify-status').text(`Checking again in ${retryAfter}s...`);
            return setTimeout((() => {
              return this.pollVerification();
            }), retryAfter * 1000);
          } else if (response.status === 'expired') {
            $('.HS-verify-banner').html(`<div style="color: #AC473B;">
    Verification expired (took too long).
    <a href="#" class="HS-verify-start" style="color: #96592A; font-weight: bold; margin-left: 6px;">Start over &rarr;</a>
</div>`);
            return $('.HS-verify-start').on('click', (e) => {
              e.preventDefault();
              return this.startVerification();
            });
          }
        },
        error: () => {
          return $('.HS-verify-status').text('Could not reach server. Try again.');
        }
      });
    }

    showVerified() {
      $('.HS-verify-banner').html(`<div>
    <span style="color: #4F934D; font-weight: bold; font-size: 13px;">&#10003; You're verified!</span>
    <span style="color: #5C5444; margin-left: 8px;">
        You can now rate commenters. Click the orbs next to any username.
    </span>
    <a href="https://${HS_SERVER}/user/${this.me}" target="_blank" style="
        color: #96592A;
        margin-left: 10px;
        font-size: 11px;
    ">View your profile &rarr;</a>
</div>`);
      // Fade out after a while
      return setTimeout((function() {
        return $('.HS-verify-banner').animate({
          opacity: 0
        }, 1000, function() {
          return $(this).parent().parent().remove();
        });
      }), 10000);
    }

    // ============================================================
    // Core functionality
    // ============================================================
    findUsernames() {
      return this.usernames = _.uniq($('a[href^=user]').map(function() {
        return $(this).attr('href').replace('user?id=', '');
      }));
    }

    loadRelationships() {
      var data;
      data = {
        u: this.usernames,
        me: this.me
      };
      if (this.auth_token) {
        data.auth_token = this.auth_token;
      }
      return $.ajax({
        url: `${window.location.protocol}//${HS_SERVER}/load`,
        data: data,
        traditional: true,
        success: this.attachRaters
      });
    }

    attachRaters(graph) {
      var $user, $users, i, len, results;
      this.graph = graph;
      $users = $('.default a[href^=user], .subtext a[href^=user]');
      console.log('Hackersmacker graph', this.graph, `${$users.length} users`);
      results = [];
      for (i = 0, len = $users.length; i < len; i++) {
        $user = $users[i];
        results.push(new HSRater($($user), this.me));
      }
      return results;
    }

    attachSharers() {}

  };

  window.HSRater = class HSRater {
    constructor($user1, me, username1) {
      this.expand = this.expand.bind(this);
      this.maybeCollapse = this.maybeCollapse.bind(this);
      this.collapse = this.collapse.bind(this);
      this.$user = $user1;
      this.me = me;
      this.username = username1;
      this.username = this.$user.attr('href').replace('user?id=', '');
      this.clear();
      this.build();
      this.attach();
      this.handle();
      return;
    }

    clear() {
      return this.$user.siblings('.HS-rater').remove();
    }

    build() {
      var $pills, foafFoe, foafFriend, foafStatus, foafTitle, graphStatus;
      foafFriend = !!_.contains(HS.graph.foaf_friends, this.username);
      foafFoe = !!_.contains(HS.graph.foaf_foes, this.username);
      graphStatus = "";
      if (_.contains(HS.graph.friends, this.username)) {
        graphStatus = "HS-friend";
      }
      if (_.contains(HS.graph.foes, this.username)) {
        graphStatus = "HS-foe";
      }
      if (foafFriend) {
        foafStatus = "HS-foaf-friend";
      }
      if (foafFoe) {
        foafStatus = "HS-foaf-foe";
      }
      foafTitle = foafFriend ? 'Friend' : 'Foe';
      $pills = $(`<div class="HS-rater ${graphStatus}" data-username="${this.username}">
  <div class="HS-rater-button HS-rater-neutral"></div>
  <div class="HS-rater-button HS-rater-friend"></div>
  <div class="HS-rater-button HS-rater-foe"></div>
</div>
<div class="HS-foaf ${foafStatus}" title="${foafTitle} of a friend">
  <div class="HS-foaf-start"></div>
  <div class="HS-foaf-end"></div>
</div>`);
      this.rater = $pills.filter('.HS-rater');
      this.foaf = $pills.filter('.HS-foaf');
      this.neutral = $('.HS-rater-neutral', this.rater);
      this.foe = $('.HS-rater-foe', this.rater);
      return this.friend = $('.HS-rater-friend', this.rater);
    }

    attach() {
      this.$user.after(this.foaf);
      return this.$user.after(this.rater);
    }

    handle() {
      this.animationOpts = {
        duration: 300,
        easing: 'easeOutQuint',
        queue: false
      };
      this.rater.filter('.HS-rater').bind('mouseenter', this.expand).bind('mouseleave', this.collapse);
      _.each([this.friend, this.foe, this.neutral], ($button) => {
        return $button.bind('click', (e) => {
          return this.save(e);
        });
      });
    }

    expand() {
      clearTimeout(this.collapseTimeout);
      this.rater.animate({
        width: 70
      }, this.animationOpts);
      this.friend.animate({
        left: 24
      }, this.animationOpts);
      return this.foe.animate({
        left: 48
      }, this.animationOpts);
    }

    maybeCollapse() {
      return this.collapseTimeout = setTimeout(() => {
        if (this.collapseTimeout) {
          return this.collapse();
        }
      }, 300);
    }

    collapse() {
      this.rater.animate({
        width: 22
      }, this.animationOpts);
      this.friend.animate({
        left: 0
      }, this.animationOpts);
      return this.foe.animate({
        left: 0
      }, this.animationOpts);
    }

    save(e) {
      var $target, context, data;
      // Block saves if not verified — nudge user to verify
      if (!HS.verified) {
        HS.showVerifyNudge();
        return;
      }
      $target = $(e.currentTarget);
      if ($target.hasClass('HS-rater-friend')) {
        this.relationship = 'friend';
        HS.graph.friends.push(this.username);
        HS.graph.foes = _.without(HS.graph.foes, this.username);
      } else if ($target.hasClass('HS-rater-foe')) {
        this.relationship = 'foe';
        HS.graph.friends = _.without(HS.graph.friends, this.username);
        HS.graph.foes.push(this.username);
      } else {
        HS.graph.friends = _.without(HS.graph.friends, this.username);
        HS.graph.foes = _.without(HS.graph.foes, this.username);
        this.relationship = 'neutral';
      }
      context = this.extractContext();
      data = {
        username: this.username,
        me: this.me,
        relationship: this.relationship,
        auth_token: HS.auth_token,
        comment_text: context.comment_text,
        comment_url: context.comment_url,
        thread_title: context.thread_title,
        thread_url: context.thread_url,
        parent_author: context.parent_author
      };
      $.ajax({
        url: `${window.location.protocol}//${HS_SERVER}/save`,
        type: 'POST',
        data: data,
        traditional: true,
        error: (xhr) => {
          if (xhr.status === 401) {
            HS.clearAuthToken();
            return HS.showWelcome();
          }
        }
      });
      console.log('Saving Hackersmacker', this.relationship, this.username, HS_SERVER);
      this.reset();
      return this.resetDuplicates();
    }

    extractContext() {
      var $ageLink, $commentRow, $commtext, $subtext, $titleLink, context, href, text;
      context = {
        comment_text: '',
        comment_url: '',
        thread_title: '',
        thread_url: window.location.href,
        parent_author: ''
      };
      // Find the comment row containing this username
      $commentRow = this.$user.closest('tr.athing.comtr');
      if (!$commentRow.length) {
        $commentRow = this.$user.closest('tr').filter(function() {
          return $(this).find('.commtext').length > 0;
        });
      }
      if ($commentRow.length) {
        // Comment text (truncate to 500 chars)
        $commtext = $commentRow.find('.commtext');
        if ($commtext.length) {
          text = $commtext.text();
          text = text.replace(/reply$/i, '').trim();
          context.comment_text = text.substring(0, 500);
        }
        // Comment permalink
        $ageLink = $commentRow.find('.age a');
        if ($ageLink.length) {
          href = $ageLink.attr('href');
          if (href) {
            if (href.indexOf('http') !== 0) {
              context.comment_url = `https://news.ycombinator.com/${href}`;
            }
          }
        }
      }
      // Thread title
      $titleLink = $('.titleline a').first();
      if (!$titleLink.length) {
        $titleLink = $('.storylink').first();
      }
      if ($titleLink.length) {
        context.thread_title = $titleLink.text().substring(0, 200);
      }
      // For submission subtext ratings (rating the submitter, not a commenter)
      $subtext = this.$user.closest('.subtext');
      if ($subtext.length) {
        context.comment_text = '';
        context.comment_url = window.location.href;
      }
      return context;
    }

    reset() {
      this.rater.removeClass('HS-foe');
      this.rater.removeClass('HS-friend');
      this.rater.addClass(`HS-${this.relationship}`);
      return this.collapse();
    }

    resetDuplicates() {
      var $dupe, $dupes, i, len, results;
      $dupes = $(`a[href^=\"user?id=${this.username}\"]`).not(this.$user);
      results = [];
      for (i = 0, len = $dupes.length; i < len; i++) {
        $dupe = $dupes[i];
        results.push(new HSRater($($dupe), this.me));
      }
      return results;
    }

  };

  $(document).ready(function() {
    return window.HS = new HSGraph();
  });

}).call(this);
