// Generated by CoffeeScript 2.6.1
(function() {
  var app, express, fs, graph;

  express = require('express');

  fs = require('fs');

  graph = require('./graph');

  // crypto = require 'crypto'

  // privateKey = fs.readFileSync('certificates/hackersmacker.key').toString()
  // certificate = fs.readFileSync('certificates/hackersmacker.crt').toString()

  // app = express.createServer key: privateKey, cert: certificate
  app = express.createServer();

  app.use(express.bodyParser());

  // CORS middleware for all requests
  app.use(function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
    if (req.method === 'OPTIONS') {
      return res.send(200);
    } else {
      return next();
    }
  });

  app.get('/load', function(req, res) {
    var originalUsername, usernames;
    originalUsername = req.query.me;
    usernames = req.query.u;
    return graph.findRelationships(originalUsername, usernames, function(m) {
      console.log(` ---> [${originalUsername}] Load ${req.headers.referer}:` + ` ${usernames.length} users -` + ` ${m.friends.length} friends, ${m.foes.length} foes,` + ` ${m.foaf_friends.length}/${m.foaf_foes.length} foaf`);
      res.contentType('json');
      return res.send(`${JSON.stringify(m)}`);
    });
  });

  app.get('/save', function(req, res) {
    var originalUsername, relationship, response, username;
    username = req.query.username;
    relationship = req.query.relationship;
    originalUsername = req.query.me;
    graph.saveRelationship(originalUsername, relationship, username);
    response = {
      code: 1,
      message: "OK"
    };
    return res.send(`${JSON.stringify(response)}`);
  });

  app.get('/safari', function(req, res) {
    return res.redirect('/safari/safari.safariextz');
  });

  app.get('/safari.safariextz', function(req, res) {
    return fs.readFile('../client/safari/Safari.safariextz', function(err, data) {
      if (err) {
        throw err;
      }
      res.contentType('application/octet-stream');
      return res.send(data);
    });
  });

  app.get('/safari.manifest.plist', function(req, res) {
    return fs.readFile('config/safari.manifest.plist', function(err, data) {
      if (err) {
        throw err;
      }
      res.contentType('application/octet-stream');
      return res.send(data);
    });
  });

  app.use(express.static(`${__dirname}/../web`));

  app.listen(3040);

}).call(this);
