// Generated by CoffeeScript 2.6.1
(function() {
  // HackerSmacker background script
  // Manages auth token storage via chrome.storage.local / browser.storage.local
  var handleMessage, ref, ref1, ref2, ref3, storage;

  storage = (typeof chrome !== "undefined" && chrome !== null ? (ref = chrome.storage) != null ? ref.local : void 0 : void 0) || (typeof browser !== "undefined" && browser !== null ? (ref1 = browser.storage) != null ? ref1.local : void 0 : void 0);

  handleMessage = function(request, sender, sendResponse) {
    switch (request.action) {
      case 'getAuthToken':
        storage.get(['hs_auth_token', 'hs_username'], function(data) {
          return sendResponse({
            auth_token: (data != null ? data.hs_auth_token : void 0) || null,
            username: (data != null ? data.hs_username : void 0) || null
          });
        });
        return true; // Keep channel open for async response
      case 'setAuthToken':
        storage.set({
          hs_auth_token: request.auth_token,
          hs_username: request.username
        }, function() {
          return sendResponse({
            success: true
          });
        });
        return true;
      case 'clearAuthToken':
        storage.remove(['hs_auth_token', 'hs_username'], function() {
          return sendResponse({
            success: true
          });
        });
        return true;
      case 'setPendingVerification':
        storage.set({
          hs_pending_token: request.token,
          hs_pending_username: request.username
        }, function() {
          return sendResponse({
            success: true
          });
        });
        return true;
      case 'getPendingVerification':
        storage.get(['hs_pending_token', 'hs_pending_username'], function(data) {
          return sendResponse({
            token: (data != null ? data.hs_pending_token : void 0) || null,
            username: (data != null ? data.hs_pending_username : void 0) || null
          });
        });
        return true;
      case 'clearPendingVerification':
        storage.remove(['hs_pending_token', 'hs_pending_username'], function() {
          return sendResponse({
            success: true
          });
        });
        return true;
    }
  };

  if (typeof chrome !== "undefined" && chrome !== null ? (ref2 = chrome.runtime) != null ? ref2.onMessage : void 0 : void 0) {
    chrome.runtime.onMessage.addListener(handleMessage);
  } else if (typeof browser !== 'undefined' && (typeof browser !== "undefined" && browser !== null ? (ref3 = browser.runtime) != null ? ref3.onMessage : void 0 : void 0)) {
    browser.runtime.onMessage.addListener(handleMessage);
  }

}).call(this);
